version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: admin_r4
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d admin_r4"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "5400:5432"
    restart: unless-stopped
    networks:
      - jara-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - jara-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  jara-network:
    driver: bridge
